### ISSUE TITLE
Add new Fonts

### ISSUE THREAD

**Issue by MD-AZMAL** [MD-AZMAL/Local-Google-Fonts#2]
Follow the contribution section in readme to know more about how to contribute

**Comment by prashi23** [comment]
Hi! I would like to work on this issue.

**Comment by MD-AZMAL** [comment]
@prashi23 sure go ahead!

**Comment by carlosfrontend** [comment]
Working on this....

I have a doubt. I think it could be implemented this way:
# font.css file

##   Lato


### Thin 
```css
@font-face {
       font-family: 'Lato';
       font-weight: 100;
       font-display:swap;
       src: url(../webfonts/Lato/Lato-Thin.ttf) format('truetype');
}
```


### Thin Italic
```css
@font-face {
       font-family: 'Lato';
       font-style: italic;
       font-weight: 100;
       font-display:swap;
       src: url(../webfonts/Lato/Lato-ThinItalic.ttf) format('truetype');
}
```

# style.css file

```css
.f11-thin {
    font-family: 'Lato';
    font-weight: 100;
}

.f11-thin-italic {
    font-family: 'Lato';
    font-weight: 100;
    font-style: italic;
}
```
# index.html file

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/fonts.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/custom.css">
    <title>Fonts Package</title>
</head>
<body>
    <p class="f11-thin">Lato Thin</p>
    <p class="f11-thin-italic">Lato Thin Italic</p>

    <footer>
        <p>&copy; <a href="http://azmal.me">Md. Azmal</a> 2019, License : MIT</p>
    </footer>
</body>
</html>
```

\* **custom.css** could be left for the user to create new classes for something else . Please Give me your opinion to see how to focus it .... Thanks, regards
![Screenshot_2019-10-06 Fonts Package(1)](https://user-images.githubusercontent.com/11649745/66263392-6ab72480-e7f2-11e9-88e3-a65fe338eeed.png)
